### ISSUE TITLE
unknown option --filter pandoc-eqnos

### ISSUE THREAD

**Issue by KristenDowns** [tomduck/pandoc-eqnos#66]
**Problem**: I am trying to run the repo code from https://github.com/ksonda/unc-dissertation-markdown-template. The 3rd README requirement is pandoc-eqnos. I followed your instructions on pandoc-eqnos installation (https://github.com/tomduck/pandoc-eqnos#installation) and have installed it under Python 3.9.12

However, I am unable to compile the md file and am getting "Unknown option --filter pandoc-eqnos." and error 6 (the same thing happens for --filter pandoc-xnos). See (1a) for YMAL for setup and (1b) for Render error in Rstudio. 

Do you know what might be causing the error? 

I've tried to supply all relevant information, but please let me know if you need anything additional as this is my first time reporting an issue on GitHub.

Thank you,
Kristen

Attachments:
1) The markdown template that uses pandoc-eqnos. I knit dissertation.Rmd to get the error. [unc-dissertation-markdown-template.zip](https://github.com/tomduck/pandoc-eqnos/files/8584400/unc-dissertation-markdown-template.zip)
2) (may not be relevant--see below) Python installation code from terminal [python_install_2022-04-28.txt](https://github.com/tomduck/pandoc-eqnos/files/8584402/python_install_2022-04-28.txt)

3) (may not be relevant--see below) Bash profile with path to location [bash_profileCOPY.txt](https://github.com/tomduck/pandoc-eqnos/files/8584401/bash_profileCOPY.txt)

1a) After downloading the repo code, I edited the YAML of dissertation.Rmd (I'm not sure if this is correct. I replaced --filter with --filter pandoc-eqnos and replace the pandoc-eqnos.exe file for the one on my computer):
```
---
bibliography: includes/bib/lit-review.bib
classoption: report
documentclass: uncdissertation
fontsize: 12pt
output:
  pdf_document:
    includes:
      before_body: includes/tex/doc_prefix_unc.tex
      fig.caption: yes
      in_header: includes/tex/header-unc.tex
    keep_tex: yes
    number_sections: yes
    pandoc_args:
    # - --filter
    - --filter pandoc-eqnos # https://github.com/tomduck/pandoc-eqnos#installation
    # - --filter pandoc-xnos # https://github.com/tomduck/pandoc-eqnos#installation
    # - C:/Python38/Scripts/pandoc-eqnos.exe # https://github.com/KristenDowns/unc-dissertation-markdown-template?organization=KristenDowns&organization=KristenDowns
    - /Users/user/Library/Python/3.9/bin/pandoc-eqnos  # https://github.com/tomduck/pandoc-eqnos#installation
    # - /Users/user/Library/Python/3.9/bin/pandoc-xnos.exe
  #   toc: no
  # word_document:
  #   toc: no
---
```

1b) Compile error occurred after running Knit in dissertation.Rmd. 
```
output file: dissertation.knit.md

Unknown option --filter pandoc-eqnos.
Try pandoc --help for more information.
Error: pandoc document conversion failed with error 6
In addition: Warning messages:
1: package 'tidyr' was built under R version 4.0.5 
2: package 'readr' was built under R version 4.0.5 
3: package 'dplyr' was built under R version 4.0.5 
4: package 'stargazer' was built under R version 4.0.5 
5: In styling_latex_scale_down(out, table_info) :
  Longtable cannot be resized.
6: In styling_latex_scale_down(out, table_info) :
  Longtable cannot be resized.
7: In styling_latex_scale_down(out, table_info) :
  Longtable cannot be resized.
Execution halted 
```

**----- Information Python / pandoc installation and bash profile paths that I set up/upgraded before trying to Knit doc and activate pandoc-eqnos, in case they are relevant-----**

2) Pandoc installation location (installation attached): '/Users/user/Library/Python/3.9/bin'

```
Requirement already satisfied: pandocfilters<2,>=1.4.2 in /usr/local/lib/python3.9/site-packages (from pandoc-xnos<3.0,>=2.5.0->pandoc-eqnos) (1.5.0)
Installing collected packages: psutil, pandoc-xnos, pandoc-eqnos
  WARNING: The script pandoc-xnos is installed in '/Users/user/Library/Python/3.9/bin' which is not on PATH.
```

3) BASH PROFILE PATH (attached): I tried adding this to my path in my .bash_profile but am not sure I did it correctly. (note: I also have PATH for Python 2.6 and 2.7, in the file and I'm not sure whether or not I should delete them.) 
```
# Setting PATH for Python 3.9
PATH="/Users/user/Library/Python/3.9/bin:${PATH}"
export PATH
```

----------------**System & Pandoc Information**-----------------------

iOS: MacOS Catalina Version 10.15.7

Rstudio: RStudio 2022.02.1+461 "Prairie Trillium" Release (8aaa5d470dd82d615130dbf663ace5c7992d48e3, 2022-03-17) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
R: 3.3.1

> Sys.info()
                                                                                             sysname 
                                                                                            "Darwin" 
                                                                                             release 
                                                                                            "19.6.0" 
                                                                                             version 
"Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64" 
                                                                                             machine 
                                                                                            "x86_64" 
                                                                                               login 
                                                                                              "root" 

> rmarkdown::pandoc_version()
[1] ‘2.17.1.1’

> system(paste(shQuote(file.path(Sys.getenv("RSTUDIO_PANDOC"), "pandoc")), "--version"))
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.2,
citeproc 0.6.0.1, ipynb 0.2

User data directory: /Users/user/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

> system("pandoc --version")
pandoc 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3,
citeproc 0.7, ipynb 0.2, hslua 2.2.0
Scripting engine: Lua 5.4
User data directory: /Users/user/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
